version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - build-target:/app/target
      - ./docker/.gitconfig:/root/.gitconfig
    working_dir: /app
    tty: true
volumes:
  build-target:
