version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - build-target:/app/target
      - ./docker/.gitconfig:/root/.gitconfig
    working_dir: /app
    tty: true
    environment:
      - JWK_URL=${JWK_URL:-https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com}
      - JWK_ISSUER=${JWK_ISSUER}
volumes:
  build-target:
